basePath: /
definitions:
  models.ALL_Status:
    properties:
      cpu:
        $ref: '#/definitions/models.CPU_Status'
      mem:
        $ref: '#/definitions/models.MEM_Status'
      net:
        $ref: '#/definitions/models.NET_Status'
    type: object
  models.CPU_Status:
    properties:
      Usage:
        type: string
      timestamp:
        type: string
    type: object
  models.HttpResponse:
    properties:
      data: {}
      status:
        $ref: '#/definitions/models.HttpStatus'
    type: object
  models.HttpStatus:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: OK
        type: string
    type: object
  models.MEM_Status:
    properties:
      available:
        description: NULL 불가
        type: integer
      timestamp:
        description: 기본 키 및 자동 생성 시간
        type: string
      total:
        description: NULL 불가
        type: integer
      used:
        description: NULL 불가
        type: integer
      usedPercent:
        description: 소수점 2자리 제한
        type: number
    type: object
  models.NET_Status:
    properties:
      bytesRecv:
        description: number of bytes received
        type: integer
      bytesSent:
        description: number of bytes sent
        type: integer
      dropin:
        description: total number of incoming packets which were dropped
        type: integer
      dropout:
        description: total number of outgoing packets which were dropped
        type: integer
      errin:
        description: total number of errors while receiving
        type: integer
      errout:
        description: total number of errors while sending
        type: integer
      fifoin:
        description: total number of FIFO buffers errors while receiving
        type: integer
      fifoout:
        description: total number of FIFO buffers errors while sending
        type: integer
      packetsRecv:
        description: number of packets received
        type: integer
      packetsSent:
        description: number of packets sent
        type: integer
      timestamp:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: MonDash API SERVER Swagger
  title: MonDash API
  version: 0.0.1
paths:
  /cpu:
    get:
      consumes:
      - application/json
      description: Retrieves CPU status data based on the specified interval and limit.
      parameters:
      - description: 'Interval in seconds (default: 1)'
        in: query
        name: interval
        type: string
      - description: 'Number of records to fetch (default: 30)'
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get CPU Status
      tags:
      - CPU
  /info:
    get:
      consumes:
      - application/json
      description: Retrieves information about the server, including hostname, OS,
        uptime, platform, and virtualization details.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get Server Information
      tags:
      - Server
  /mem:
    get:
      consumes:
      - application/json
      description: Retrieves memory status data based on the specified interval and
        limit.
      parameters:
      - description: 'Interval in seconds (default: 1)'
        in: query
        name: interval
        type: string
      - description: 'Number of records to fetch (default: 30)'
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get Memory Status
      tags:
      - Memory
  /net:
    get:
      consumes:
      - application/json
      description: Retrieves network status data based on the specified interval and
        limit.
      parameters:
      - description: 'Interval in seconds (default: 1)'
        in: query
        name: interval
        type: string
      - description: 'Number of records to fetch (default: 30)'
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get Network Status
      tags:
      - Network
  /ws:
    get:
      description: Handles WebSocket connections and streams system status updates
        (CPU, Memory, Network) every second.
      responses:
        "200":
          description: System status updates are sent via WebSocket.
          schema:
            $ref: '#/definitions/models.ALL_Status'
      summary: WebSocket Endpoint
      tags:
      - WebSocket
swagger: "2.0"
