basePath: /
definitions:
  models.HttpResponse:
    properties:
      data: {}
      status:
        $ref: '#/definitions/models.HttpStatus'
    type: object
  models.HttpStatus:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: OK
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: MonDash API SERVER Swagger
  title: MonDash API
  version: 0.0.1
paths:
  /cpu:
    get:
      consumes:
      - application/json
      description: Retrieves CPU status data based on the specified interval and limit.
      parameters:
      - description: 'Interval in seconds (default: 1)'
        in: query
        name: interval
        type: string
      - description: 'Number of records to fetch (default: 30)'
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get CPU Status
      tags:
      - CPU
  /info:
    get:
      consumes:
      - application/json
      description: Retrieves information about the server, including hostname, OS,
        uptime, platform, and virtualization details.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get Server Information
      tags:
      - Server
  /mem:
    get:
      consumes:
      - application/json
      description: Retrieves memory status data based on the specified interval and
        limit.
      parameters:
      - description: 'Interval in seconds (default: 1)'
        in: query
        name: interval
        type: string
      - description: 'Number of records to fetch (default: 30)'
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get Memory Status
      tags:
      - Memory
  /net:
    get:
      consumes:
      - application/json
      description: Retrieves network status data based on the specified interval and
        limit.
      parameters:
      - description: 'Interval in seconds (default: 1)'
        in: query
        name: interval
        type: string
      - description: 'Number of records to fetch (default: 30)'
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Get Network Status
      tags:
      - Network
swagger: "2.0"
